### ISSUE TITLE
How to use this container?

### ISSUE THREAD

**Issue by x64life** [ich777/unraid_kernel#4]
Hi ich777, 
I want to add ashmen and binder into my Unraid server, but how can I use this container to do it?
I have looked the example, and I think it is a little hard for me to create shell command for ashmen and binder😓.
Do you have some tutorials? Thank you

**Comment by ich777** [comment]
This container is basically only meant to compile 3rd party drivers for Unraid, pack them up for a plugin so that this package can be installed through a plugin on boot to Unraid.
Please correct me if I'm wrong but the two modules you are talking about are for Android correct?

Do you have a source for me so that I can look into it?  
Have you yet compiled the two modules on a different OS for a `x86_64` Kernel?

The basic steps are:

1. Put the template file from the template folder in the appropriate folder on you USB Boot device (as described in the [README.md](https://github.com/ich777/unraid_kernel/blob/master/template/README.md) in the template folder) Start the container, wait for it to pull the necessary files and prepare the Kernel (watch the container log)
2. Open up a container console or connect through SSH to the container
3. Compile your modules
4. Pack them
5. Maybe upload them to GitHub for your plugin

The examples what you've looked at is basically all the steps that I've described above from step 2.

**Comment by x64life** [comment]
Thank you.
I  want run this docker:
https://hub.docker.com/r/redroid/redroid
It needs binder and ashmem modules first. I will try to install these modules.

**Comment by ich777** [comment]
> It needs binder and ashmem modules first. I will try to install these modules.

From where do you get the source from these modules for `x86_64`?
I can help setting up a plugin if that's a thing from interest for you.

Feel free to reach out again if you need anything.

**Comment by x64life** [comment]
Follow your guide, I have compiled the binder module to .txz file, how can I install it to Unraid server?
The modules source are here:
https://github.com/remote-android/redroid-modules

**Comment by ich777** [comment]
> Follow your guide, I have compiled the binder module to .txz file, how can I install it to Unraid server?

For testing I would recommend that you put the file on Unraid, then navigate in the terminal to the file location where you've put the file, issue `installpkg <PKGNAME.txz>`, issue `depmod -a`, issue `modprobe binderfs` & `modprobe ashmem`.

If that all went well and is working, alongside with your Docker container where these modules are needed, we can move on and create a plugin if you want to make it available to others.

**Comment by ich777** [comment]
@x64life any update on this? Is all working?

**Comment by x64life** [comment]
> @x64life any update on this? Is all working?

Hi ich777, I have built these two modules, and use modprobe to install.  I don't know if it is OK. I am trying to run the DeDroid docker, now has some issues and try to fix. Thank you

**Comment by ich777** [comment]
Which issues are you experiencing?
Do the modules load correctly or better speaking do you see them listed after the modprobe when issuing `lsmod`?

**Comment by x64life** [comment]
Last login: Fri Oct 27 13:59:29 2023 from 192.168.99.4
Linux 6.1.49-Unraid.
root@MyHomeServer:~# lsmod | grep ashmem
ashmem_linux           16384  0
root@MyHomeServer:~# lsmod | grep binder
binder_linux          184320  0

**Comment by x64life** [comment]
Success to run redroid. Tks

**Comment by ich777** [comment]
> Success to run redroid. Tks

Glad that I could help, Would you like to create a plugin from that so that other users can benefit from it too?

**Comment by x64life** [comment]
Although the docker running, but still have an issue on the binder driver. The docker logcat show "Can't open /dev/binder: Permission denied"

**Comment by x64life** [comment]
redroid also need ION or DMA-BUF Heaps. I don't know if the issue caused by this. Try to solve

**Comment by ich777** [comment]
> Although the docker running, but still have an issue on the binder driver. The docker logcat show "Can't open /dev/binder: Permission denied"

Sounds like a permission issue. I can't help much here because I don't know this container nor the modules.

**Comment by r4lix** [comment]
> Success to run redroid. Tks

Hello, sorry to resurect, do you mind sharing your kernel ? I want to run redroid too

**Comment by ich777** [comment]
> > Success to run redroid. Tks
> 
> Hello, sorry to resurect, do you mind sharing your kernel ? I want to run redroid too

I think that it never run properly from what I understand because of `/dev/binder` but I'm not sure because the user never responded after my answer.

**Comment by r4lix** [comment]
I have Kasm Workspaces that include a Redroid image but because of binder_linux it's not working

![Image](https://github.com/user-attachments/assets/cf3e6c62-a3e0-4737-8fdd-42c5b981b970)

Do you think it's possible for you to guide me how to add binder_linux to unraid ? I found this repo (https://github.com/thor2002ro/unraid_kernel/releases/tag/20250326) that have binder_linux but lacks Nvidia driver

**Comment by ich777** [comment]
> Do you think it's possible for you to guide me how to add binder_linux to unraid ?

1. Start [here](https://github.com/ich777/unraid_kernel/issues/4#issuecomment-1777152024)
2. Then you have to find the modules for `binder` and `ashmem` in the `.config` file and enable them
3. After that you can compile the modules
4. Create a package or simply copy them to Unraid
5. Run `depmod --all` on Unraid
6. Do `modprobe binder ashmem` on Unraid

Sorry I can't do anything else since if something isn't working I can't help, I've never run the container myself.

**Comment by r4lix** [comment]
@ich777 is it possible to bypass the kernel check on your nvidia driver ? I can then install this custom kernel [https://github.com/thor2002ro/unraid_kernel](url) that include binder

**Comment by ich777** [comment]
> [@ich777](https://github.com/ich777) is it possible to bypass the kernel check on your nvidia driver ? I can then install this custom kernel [https://github.com/thor2002ro/unraid_kernel](url) that include binder

No because them the driver wont work.

Maybe I can get the necessary modules into the Unraid Kernel.

**Comment by r4lix** [comment]
> > [@ich777](https://github.com/ich777) is it possible to bypass the kernel check on your nvidia driver ? I can then install this custom kernel [https://github.com/thor2002ro/unraid_kernel](url) that include binder
> 
> No because them the driver wont work.
> 
> Maybe I can get the necessary modules into the Unraid Kernel.

That would be amazing ! Thank you for your work ! Take your time !

**Comment by ich777** [comment]
Please see my post [here](https://forums.unraid.net/topic/149453-redroid-on-unraid/#findComment-1545510).
